'use server';

/**
 * @fileOverview Implements the counter-analysis flow.
 * 
 * This flow takes an existing analysis and a new, external analysis, 
 * and provides a synthesized critique and second opinion from the perspective 
 * of a different AI persona, "iaedge".
 * 
 * - counterAnalysis - The main function for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const CounterAnalysisInputSchema = z.object({
    originalAnalysis: z.string().describe("The original analysis markdown text generated by 'Inverapuestas Pro'."),
    externalAnalysis: z.string().describe("A new analysis from an external source, provided by the user."),
});
export type CounterAnalysisInput = z.infer<typeof CounterAnalysisInputSchema>;

const CounterAnalysisOutputSchema = z.object({
    counterAnalysis: z.string().describe("The synthesized counter-analysis markdown text generated by 'iaedge'."),
});
export type CounterAnalysisOutput = z.infer<typeof CounterAnalysisOutputSchema>;


export async function counterAnalysis(input: CounterAnalysisInput): Promise<CounterAnalysisOutput> {
  return counterAnalysisFlow(input);
}


const counterAnalysisPrompt = ai.definePrompt({
  name: 'counterAnalysisPrompt',
  input: { schema: CounterAnalysisInputSchema },
  output: { schema: CounterAnalysisOutputSchema },
  prompt: `¡Hola! Soy **iaedge** 🤖, tu especialista en síntesis y análisis crítico de apuestas. Mi trabajo es fusionar diferentes perspectivas para darte la visión más completa.

He recibido dos análisis sobre un cupón de apuestas:
1.  **Análisis Original (de "Inverapuestas Pro")**
2.  **Análisis Externo (proporcionado por ti)**

**Tu Misión:**
Actúa como "iaedge" y genera un único informe en formato Markdown y en español que **sintetice, compare y contraste** ambos análisis. No critiques por criticar; tu objetivo es **extraer el máximo valor de ambas fuentes**.

**Estructura OBLIGATORIA de tu informe:**

1.  **Síntesis General:**
    *   Comienza con un párrafo resumen. ¿Son los análisis mayormente convergentes o divergentes? ¿Qué nuevas perspectivas aporta el análisis externo?

2.  **Análisis Comparativo por Partido:**
    *   Para cada partido presente en el análisis original, compáralo con la visión del análisis externo si también lo cubre.
    *   Usa emojis para señalar el grado de acuerdo:
        *   🤝 **Convergencia:** Ambos análisis llegan a una conclusión similar (ej. ambos ven valor en la misma selección).
        *   🤔 **Divergencia/Matiz:** Uno de los análisis ofrece un punto de vista diferente, un dato clave que el otro omitió, o llega a una conclusión de valor opuesta. Explica el porqué de la diferencia.
        *   🆕 **Nueva Perspectiva:** El análisis externo aporta un dato completamente nuevo (ej. una lesión de última hora, una estadística H2H relevante que no se consideró).

3.  **Partidos Nuevos (si los hay):**
    *   Si el análisis externo incluye partidos que no estaban en el cupón original, analízalos brevemente bajo el título "Partidos Adicionales del Análisis Externo".

4.  **Tabla de Valor Consolidada:**
    *   Crea una **única** "TABLA DE APUESTAS DE VALOR" en Markdown.
    *   **CRÍTICO:** Incluye **SOLAMENTE** las selecciones donde **AMBOS** análisis (o la síntesis final de "iaedge") coinciden en que hay valor positivo (EV > 0). Si solo uno lo ve, no lo incluyas. Sé conservador.
    *   **CRÍTICO:** Ordena la tabla de MAYOR a MENOR "Valor Calculado", usando los datos del análisis original o un promedio si tiene sentido.

5.  **Conclusión y Veredicto de "iaedge":**
    *   Finaliza con 2-3 puntos clave. ¿Qué análisis parece más robusto? ¿La información externa cambia la estrategia de apuestas recomendada? ¿Cuál es tu recomendación final como "iaedge"?

**Análisis Original (de Inverapuestas Pro):**
\`\`\`markdown
{{{originalAnalysis}}}
\`\`\`

**Análisis Externo (proporcionado por el usuario):**
\`\`\`markdown
{{{externalAnalysis}}}
\`\`\`

Ahora, genera el informe de síntesis y contra-análisis completo como "iaedge". Sé riguroso, objetivo y aporta claridad.`,
    config: {
      temperature: 0.2
    }
});


const counterAnalysisFlow = ai.defineFlow(
  {
    name: 'counterAnalysisFlow',
    inputSchema: CounterAnalysisInputSchema,
    outputSchema: CounterAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await counterAnalysisPrompt(input);
    if (!output) {
      throw new Error("No se pudo generar el contra-análisis.");
    }
    return { counterAnalysis: output.counterAnalysis };
  }
);
