'use server';

/**
 * @fileOverview Implements the counter-analysis flow.
 * 
 * This flow takes an existing analysis and a new, external analysis, 
 * and provides a synthesized critique and second opinion from the perspective 
 * of a different AI persona, "iaedge".
 * 
 * - counterAnalysis - The main function for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const CounterAnalysisInputSchema = z.object({
    originalAnalysis: z.string().describe("The original analysis markdown text generated by 'Inverapuestas Pro'."),
    externalAnalysis: z.string().describe("A new analysis from an external source, provided by the user."),
});
export type CounterAnalysisInput = z.infer<typeof CounterAnalysisInputSchema>;

const CounterAnalysisOutputSchema = z.object({
    counterAnalysis: z.string().describe("The synthesized counter-analysis markdown text generated by 'iaedge'."),
});
export type CounterAnalysisOutput = z.infer<typeof CounterAnalysisOutputSchema>;


export async function counterAnalysis(input: CounterAnalysisInput): Promise<CounterAnalysisOutput> {
  return counterAnalysisFlow(input);
}


const counterAnalysisPrompt = ai.definePrompt({
  name: 'counterAnalysisPrompt',
  input: { schema: CounterAnalysisInputSchema },
  output: { schema: CounterAnalysisOutputSchema },
  prompt: `Eres "iaedge" 🤖, un analista comparativo de élite especializado en fusionar múltiples perspectivas de inversión deportiva. Tu proceso es riguroso y lógico. Se te han proporcionado dos análisis: uno de "Inverapuestas Pro" (el original) y otro de una fuente externa.

**Tu Misión en 2 Pasos:**

**Paso 1: Deconstrucción Lógica (Análisis Interno):**
Primero, deconstruye mentalmente cada análisis en sus componentes fundamentales:
*   **Conclusión principal:** ¿Cuál es la predicción final? (Ej: "Victoria del Jugador A").
*   **Premisas de apoyo:** ¿Qué argumentos o datos se usan para justificar esa conclusión? (Ej: "Dominio en la superficie", "H2H favorable").
*   **Riesgos o Contraargumentos:** ¿Qué debilidades o factores en contra se mencionan? (Ej: "Bajo % de primer servicio", "Fatiga reciente").

**Paso 2: Informe de Síntesis Comparativa (Tu Salida en Markdown):**
Basado en tu deconstrucción interna, ahora genera un informe en español y formato Markdown que mapee las relaciones lógicas y ofrezca una conclusión sintetizada. Usa esta estructura OBLIGATORIA:

1.  **Veredicto General:**
    *   Comienza con un párrafo conciso. ¿Las conclusiones principales coinciden o chocan? ¿Qué análisis parece más robusto y por qué?

2.  **Mapeo de Relaciones Lógicas:**
    *   **Puntos de Acuerdo (🤝):** Lista los argumentos o conclusiones en los que ambos análisis están de acuerdo.
    *   **Puntos de Divergencia (🤔):** Describe los puntos clave de conflicto, explicando la diferencia en el razonamiento.
    *   **Argumentos Únicos de Inverapuestas Pro (💡):** Lista los puntos clave que solo el análisis original mencionó.
    *   **Argumentos Únicos del Análisis Externo (🆕):** Lista los puntos clave que solo el análisis externo aportó.

3.  **Tabla de Valor Consolidada:**
    *   Crea una **única** "TABLA DE APUESTAS DE VALOR" en Markdown.
    *   **CRÍTICO:** Incluye **SOLAMENTE** las selecciones donde, tras tu análisis comparativo, sigues viendo un consenso o una fuerte evidencia de valor positivo (EV > 0). Sé conservador. Si un análisis desacredita fuertemente al otro, es posible que no haya ninguna apuesta de valor consolidada.

4.  **Conclusión Final de "iaedge":**
    *   Finaliza con tu recomendación experta. ¿Qué acción sugieres? ¿Se debería mantener la apuesta original, modificarla, o quizás no hacer nada? Justifica tu veredicto final basándote en la síntesis.

**Análisis Original (de Inverapuestas Pro):**
\`\`\`markdown
{{{originalAnalysis}}}
\`\`\`

**Análisis Externo (proporcionado por el usuario):**
\`\`\`markdown
{{{externalAnalysis}}}
\`\`\`

Ahora, ejecuta tu proceso de dos pasos y genera el informe de síntesis comparativa como "iaedge".`,
    config: {
      temperature: 0.2
    }
});


const counterAnalysisFlow = ai.defineFlow(
  {
    name: 'counterAnalysisFlow',
    inputSchema: CounterAnalysisInputSchema,
    outputSchema: CounterAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await counterAnalysisPrompt(input);
    if (!output) {
      throw new Error("No se pudo generar el contra-análisis.");
    }
    return { counterAnalysis: output.counterAnalysis };
  }
);
