'use server';

/**
 * @fileOverview Implements the counter-analysis flow.
 * 
 * This flow takes a structured deconstruction of an original analysis and an external analysis,
 * and provides a synthesized critique and second opinion from the perspective 
 * of a different AI persona, "iaedge".
 * 
 * - counterAnalysis - The main function for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { DeconstructedAnalysisSchema } from '@/lib/types/analysis';

const CounterAnalysisInputSchema = z.object({
    inverapuestasAnalysis: DeconstructedAnalysisSchema,
    externalAnalysis: DeconstructedAnalysisSchema,
});
export type CounterAnalysisInput = z.infer<typeof CounterAnalysisInputSchema>;

const CounterAnalysisOutputSchema = z.object({
    counterAnalysis: z.string().describe("The synthesized counter-analysis markdown text generated by 'iaedge'."),
});
export type CounterAnalysisOutput = z.infer<typeof CounterAnalysisOutputSchema>;


export async function counterAnalysis(input: CounterAnalysisInput): Promise<CounterAnalysisOutput> {
  return counterAnalysisFlow(input);
}


const counterAnalysisPrompt = ai.definePrompt({
  name: 'counterAnalysisPrompt',
  input: { schema: CounterAnalysisInputSchema },
  output: { schema: CounterAnalysisOutputSchema },
  prompt: `Eres "iaedge" 🤖, un analista comparativo de élite especializado en fusionar múltiples perspectivas de inversión deportiva. Se te han proporcionado dos análisis ya deconstruidos en su estructura lógica.

**Tu Misión:**
Genera un informe de síntesis comparativa en español y formato Markdown. Tu informe debe mapear las relaciones lógicas entre los dos análisis y ofrecer una conclusión sintetizada. Utiliza esta estructura OBLIGATORIA:

1.  **Veredicto General:**
    *   Comienza con un párrafo conciso. ¿Las conclusiones principales coinciden o chocan? ¿Qué análisis parece más robusto y por qué?

2.  **Mapeo de Relaciones Lógicas:**
    *   **Puntos de Acuerdo (🤝):** Lista los argumentos o conclusiones en los que ambos análisis están de acuerdo.
    *   **Puntos de Divergencia (🤔):** Describe los puntos clave de conflicto, explicando la diferencia en el razonamiento.
    *   **Argumentos Únicos de Inverapuestas Pro (💡):** Lista los puntos clave que solo el análisis original mencionó.
    *   **Argumentos Únicos del Análisis Externo (🆕):** Lista los puntos clave que solo el análisis externo aportó.

3.  **Tabla de Valor Consolidada:**
    *   Crea una **única** "TABLA DE APUESTAS DE VALOR" en Markdown.
    *   **CRÍTICO:** Incluye **SOLAMENTE** las selecciones donde, tras tu análisis comparativo, sigues viendo un consenso o una fuerte evidencia de valor positivo (EV > 0). Sé conservador.

4.  **Conclusión Final de "iaedge":**
    *   Finaliza con tu recomendación experta. ¿Qué acción sugieres? ¿Se debería mantener la apuesta original, modificarla, o quizás no hacer nada? Justifica tu veredicto final.

**Datos de los Análisis Deconstruidos:**
\`\`\`json
{{{jsonStringify this}}}
\`\`\`

Ahora, genera el informe de síntesis comparativa como "iaedge".`,
    config: {
      temperature: 0.2
    }
});


const counterAnalysisFlow = ai.defineFlow(
  {
    name: 'counterAnalysisFlow',
    inputSchema: CounterAnalysisInputSchema,
    outputSchema: CounterAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await counterAnalysisPrompt(input);
    if (!output) {
      throw new Error("No se pudo generar el contra-análisis.");
    }
    return { counterAnalysis: output.counterAnalysis };
  }
);
