# Este archivo definirá el entorno de nuestro contenedor Docker.
# Se utilizará para desplegar nuestra aplicación en Google Cloud Run (a través de Cloud Functions Gen 2).
# Especificará la versión de Python, instalará las dependencias de 'requirements.txt'
# y, crucialmente, ejecutará los comandos necesarios para instalar los navegadores de Playwright.
